# Generated by Django 5.1.7 on 2025-03-19 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0006_promo'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='promos',
            field=models.ManyToManyField(blank=True, to='checkout.promo'),
        ),
    ]
