# Generated by Django 5.1.7 on 2025-03-19 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0007_order_promos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='promos',
        ),
        migrations.AddField(
            model_name='order',
            name='vat_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
