# Generated by Django 5.1.7 on 2025-03-16 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0008_alter_orderlineitem_lineitem_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderlineitem',
            old_name='shoe_size',
            new_name='shoe_sizes',
        ),
    ]
