# Generated by Django 5.1.7 on 2025-03-20 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20250310_2229'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='shoe_sizes',
            new_name='product_size',
        ),
    ]
