# Generated by Django 5.1.7 on 2025-03-20 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_shoe_sizes_product_product_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_size',
            new_name='shoe_sizes',
        ),
    ]
